### ISSUE TITLE
Function to destroy and re init

### ISSUE THREAD

**Issue by CWijaya** [peacepostman/wavify#1]
Hi, is it possible to destroy and reinit the elements? I tried to destroy it using TweenMax.killTweensOf(), but it didn't work. Removing and appending the elements didn't work either. Is there any other way? Thanks!

**Comment by peacepostman** [comment]
Hello ! Unfortunately I have very few free time ATM :/ I'll try to add this as soon as I have time, feel free to submit a PR ;)

**Comment by joeyparis** [comment]
I have somewhat solved this with pull request #4. Not the ability to destroy and re-init, but the ability to at least redefine the options after the original initialization

**Comment by peacepostman** [comment]
Hello, i've added those feature, please have a try with play, pause, kill and reboot function. I've updated the docs.
