### ISSUE TITLE
Change options after init

### ISSUE THREAD

**Issue by arjunmenon** [peacepostman/wavify#2]
Hey
Nice plugin.
How can we alter the options like speed, amplitude, bone, color after we have initialized those options?
Also can we start/stop the animation.

**Comment by NicolasMrc** [comment]
The way i'm doing it is by redefining the wavify() plugin it works, the only problem is that after some reset it's seems to lag.
I have that code if you want to try (it can be improved i'msure of it) :

    updateWaves(active, color){
        $("#wave-one").wavify({
          height: active ? 20 : 90,
          bones: 4,
          amplitude: active ? 30 : 0,
          color: '"rgba("+color.r+","+color.g+","+color.b+",.1)",
          speed: .25
        });

        $("#wave-two").wavify({
          height: active ? 10 : 80,
          bones: 3,
          amplitude: active ? 40 : 0,
          color: "rgba("+color.r+","+color.g+","+color.b+",.2)" ,
          speed: .25
        });
      },

here `color` is a json containing r, g and b values of the color and `active` is a boolean telling if the wave is paused or not (paused is set to be low and grey)

**Comment by arjunmenon** [comment]
That looks like a nice hack.
I haven't tested though at first hunch, reinitializing the waves might handle the lag. I am still trying to understand the Tween library but plugin itself needs to be modified to introduce destroy.

**Comment by joeyparis** [comment]
I have created a quick and dirty solution for this in pull request #4 although it is branched off of pull request #3. The only requirement to get that solution to work is that each wave must have a unique ID.

**Comment by arjunmenon** [comment]
Anybody reading this thread, be known, this plugin though really really nice, introduces serious performance issues in limited setups, like mobile.
I have experienced some really aggressive heating issues when trying out as a decorative element in the page with nothing else.
This may be perhaps  on each interval it draws a new Tween object.

Apart from this, there is everything to like about this plugin.

@joeyparis To be clear, to alter the wave after init, we would have to call wavify again with the same params?

**Comment by joeyparis** [comment]
@arjunmenon You have to call the wavify function again on the same element, but the params can be different

**Comment by peacepostman** [comment]
I've added some available methods for the plugin, please have a try and give me feedbacks.

Thanks for your requests
